# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e46fe5317c71ce976e64a916863fe213"
name = "Orderly"
application_url = "https://orderly-be.test/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_draft_orders,customer_read_markets,customer_read_orders,customer_write_customers,customer_write_orders,read_analytics,read_app_proxy,read_customer_events,read_customers,read_products,write_app_proxy,write_customers,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
